"""services/architecture/workers/api_architect.py — APIArchitect L5 worker."""
from __future__ import annotations
import json
from core.contracts import AgentResult, TaskStatus
from core.runtime.base_agent import BaseAgent
from core.runtime.context import ReviewCycle, TaskInput
from core.runtime.factory import AgentFactory

def _parse(raw, fb=None):
    try:
        c=raw.strip()
        if c.startswith("```"): c=c.split("```")[1]; c=c[4:] if c.startswith("json") else c
        return json.loads(c.strip())
    except Exception: return fb or {}

@AgentFactory.register("api_architect_worker")
class APIArchitectWorker(BaseAgent):
    """Produces api_spec (OpenAPI 3.1). Consumes architecture_blueprint."""
    async def execute(self, task: TaskInput) -> AgentResult:
        ctx   = task.context
        bp    = ctx.get_artifact("architecture_blueprint", {})
        reqs  = ctx.get_artifact("requirements_doc", {})
        stories = ctx.get_artifact("user_stories_doc", {})

        services  = bp.get("services", [])        if isinstance(bp, dict) else []
        req_list  = reqs.get("requirements", [])  if isinstance(reqs, dict) else []
        story_list= stories.get("user_stories",[]) if isinstance(stories, dict) else []
        func_reqs = [r for r in req_list if r.get("category") == "functional"]

        sys = self.build_system_prompt(task)
        revision = f"\n\nREVISION FEEDBACK:\n{task.revision_feedback}" if task.revision_feedback else ""
        raw, usage = await self.call_llm(task, [{"role":"system","content":sys},{"role":"user","content":f"""Generate a complete OpenAPI 3.1 specification covering all services.

SERVICES: {json.dumps([{{"name":s.get("name"),"prefix":f"/api/v1/{s.get('name','').replace('-','_')}","port":s.get("port")}} for s in services[:8]], indent=2)}
FUNCTIONAL REQUIREMENTS ({len(func_reqs)}): {json.dumps(func_reqs[:8], indent=2)}
USER STORIES ({len(story_list)}): {json.dumps(story_list[:6], indent=2)}
{revision}

Rules:
- Every functional requirement must have at least one endpoint
- Every operationId must be unique (format: verbResourceNoun e.g. createProject)
- Every endpoint must have 200/201, 400, 401, and 404 responses defined
- All protected endpoints must have bearerAuth security

Return ONLY valid OpenAPI 3.1 JSON:
{{
  "openapi": "3.1.0",
  "info": {{"title": "Project API", "version": "1.0.0", "description": "Generated by AASC"}},
  "servers": [{{"url": "/api/v1", "description": "API v1"}}],
  "security": [{{"bearerAuth": []}}],
  "paths": {{
    "/health": {{
      "get": {{
        "operationId": "healthCheck",
        "summary": "Health check",
        "security": [],
        "responses": {{"200": {{"description": "OK", "content": {{"application/json": {{"schema": {{"type":"object","properties":{{"status":{{"type":"string"}}}}}}}}}}}}}}
      }}
    }}
  }},
  "components": {{
    "schemas": {{
      "Error": {{"type":"object","properties":{{"detail":{{"type":"string"}}}}}},
      "Pagination": {{"type":"object","properties":{{"total":{{"type":"integer"}},"page":{{"type":"integer"}}}}}}
    }},
    "securitySchemes": {{
      "bearerAuth": {{"type":"http","scheme":"bearer","bearerFormat":"JWT"}}
    }}
  }},
  "quality_score": 0.0
}}"""}], max_tokens=4096)

        content = _parse(raw, {"openapi":"3.1.0","paths":{},"components":{},"quality_score":0.0})
        endpoint_count = len(content.get("paths", {}))
        review  = await ReviewCycle(self).run(content, task, schema={"root":["openapi","info","paths","components"]})
        if not review.passed:
            return self.escalate(task, f"API spec failed validation after {review.cycles_run} cycles")
        artifact = await self.create_artifact(task, "api_spec",
            {**content, "project_id":task.project_id, "endpoint_count":endpoint_count})
        await self.write_memory(task, f"API spec: {endpoint_count} endpoints defined across {len(services)} services", source="api_architect")
        return AgentResult(task_id=task.task_id, agent_id=self.agent_id, status=TaskStatus.COMPLETED,
            content=content, summary=f"API spec: {endpoint_count} endpoints (OpenAPI 3.1)",
            quality_score=review.final_score, artifacts=[artifact], token_usage=usage)
