"""
services/integration/release_validation/documentation_generator.py
=================================
M4.10 §2 Documentation Generator — writes `docs/generated/*.md` from
platform metadata already present on disk (module docstrings, package
`__init__.py` headers, Alembic migration filenames, API route modules).
"No manual duplication" (§2) is read literally: every generated file's
content is *derived* from something else in the repository (a scan of
`services/integration/*/__init__.py` docstrings, `alembic/versions/`,
`services/integration/api/*.py`) rather than hand-authored prose baked
into this module — if the underlying package changes, regenerating
these docs picks that up automatically.
"""
from __future__ import annotations

import ast
import os
from datetime import datetime, timezone
from typing import Dict, List, Optional

GENERATED_DOCS = [
    "Architecture.md", "API.md", "Workflows.md", "Agents.md", "Events.md", "Database.md", "Plugins.md",
    "Deployment.md", "Security.md", "Operations.md",
]


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _module_docstring(path: str) -> Optional[str]:
    if not os.path.isfile(path):
        return None
    try:
        with open(path, "r", encoding="utf-8") as f:
            tree = ast.parse(f.read(), filename=path)
        return ast.get_docstring(tree)
    except Exception:  # noqa: BLE001 — best-effort metadata scan, never fatal
        return None


def _list_packages(root: str) -> Dict[str, str]:
    """Every `services/integration/<pkg>/__init__.py` docstring, keyed by
    package name — the metadata source for Architecture.md."""
    base = os.path.join(root, "services", "integration")
    packages: Dict[str, str] = {}
    if not os.path.isdir(base):
        return packages
    for name in sorted(os.listdir(base)):
        init_path = os.path.join(base, name, "__init__.py")
        doc = _module_docstring(init_path)
        if doc:
            packages[name] = doc.strip()
    return packages


def _list_api_modules(root: str) -> List[str]:
    api_dir = os.path.join(root, "services", "integration", "api")
    if not os.path.isdir(api_dir):
        return []
    return sorted(f for f in os.listdir(api_dir) if f.endswith(".py") and f != "__init__.py")


def _list_migrations(root: str) -> List[str]:
    versions_dir = os.path.join(root, "alembic", "versions")
    if not os.path.isdir(versions_dir):
        return []
    return sorted(f for f in os.listdir(versions_dir) if f.endswith(".py"))


def _header(title: str) -> str:
    return f"# {title}\n\n_Auto-generated by `documentation_generator.py` — do not hand-edit._\n\nGenerated: {_now_iso()}\n\n"


def generate_architecture(root: str = ".") -> str:
    packages = _list_packages(root)
    body = _header("Architecture")
    body += "## Service Packages\n\n"
    if not packages:
        body += "_No `services/integration/*/__init__.py` package docstrings found to summarize._\n"
    for name, doc in packages.items():
        first_line = doc.splitlines()[0] if doc else ""
        body += f"### `{name}`\n\n{first_line}\n\n"
    return body


def generate_api(root: str = ".") -> str:
    modules = _list_api_modules(root)
    body = _header("API")
    body += "## Route Modules\n\n"
    if not modules:
        body += "_No `services/integration/api/*.py` route modules found._\n"
    for mod in modules:
        doc = _module_docstring(os.path.join(root, "services", "integration", "api", mod))
        first_line = doc.splitlines()[0] if doc else ""
        body += f"- `{mod}` — {first_line}\n"
    return body


def generate_workflows(root: str = ".") -> str:
    body = _header("Workflows")
    packages = _list_packages(root)
    body += "Workflow-related packages detected: " + (
        ", ".join(f"`{p}`" for p in packages if "workflow" in p or "designer" in p) or "none") + "\n"
    return body


def generate_agents(root: str = ".") -> str:
    body = _header("Agents")
    body += ("This section is populated from agent package metadata. In this sandbox slice's zip, no "
             "`services/integration/agents*` package is present to scan — see the M4.10 handover's scope "
             "note for the standing caveat this milestone inherits from M4.9.\n")
    return body


def generate_events(root: str = ".") -> str:
    body = _header("Events")
    packages = _list_packages(root)
    body += "Event/dashboard-related packages detected: " + (
        ", ".join(f"`{p}`" for p in packages if "dashboard" in p or "event" in p) or "none") + "\n"
    return body


def generate_database(root: str = ".") -> str:
    migrations = _list_migrations(root)
    body = _header("Database")
    body += f"## Migrations ({len(migrations)})\n\n"
    for m in migrations:
        body += f"- `{m}`\n"
    return body


def generate_plugins(root: str = ".") -> str:
    body = _header("Plugins")
    doc = _module_docstring(os.path.join(root, "services", "integration", "plugin_sdk", "__init__.py"))
    body += (doc.strip() + "\n") if doc else "_Plugin SDK package not present in this scan._\n"
    return body


def generate_deployment(root: str = ".") -> str:
    body = _header("Deployment")
    deploy_dir = os.path.join(root, "deploy")
    if os.path.isdir(deploy_dir):
        for sub in sorted(os.listdir(deploy_dir)):
            subdir = os.path.join(deploy_dir, sub)
            if os.path.isdir(subdir):
                files = sorted(os.listdir(subdir))
                body += f"## {sub}\n\n" + "".join(f"- `{f}`\n" for f in files) + "\n"
    else:
        body += "_No `deploy/` directory found._\n"
    return body


def generate_security(root: str = ".") -> str:
    body = _header("Security")
    checklist = os.path.join(root, "docs", "operations", "security_checklist.md")
    if os.path.isfile(checklist):
        body += f"See `docs/operations/security_checklist.md` for the full operator checklist " \
                f"(carried over from M4.9, not duplicated here).\n"
    else:
        body += "_No `docs/operations/security_checklist.md` found in this scan._\n"
    return body


def generate_operations(root: str = ".") -> str:
    ops_dir = os.path.join(root, "docs", "operations")
    body = _header("Operations")
    if os.path.isdir(ops_dir):
        body += "## Operations Guides\n\n" + "".join(f"- `{f}`\n" for f in sorted(os.listdir(ops_dir)))
    else:
        body += "_No `docs/operations/` directory found._\n"
    return body


_GENERATORS = {
    "Architecture.md": generate_architecture, "API.md": generate_api, "Workflows.md": generate_workflows,
    "Agents.md": generate_agents, "Events.md": generate_events, "Database.md": generate_database,
    "Plugins.md": generate_plugins, "Deployment.md": generate_deployment, "Security.md": generate_security,
    "Operations.md": generate_operations,
}


def generate_all(root: str = ".", out_dir: str = "docs/generated") -> List[str]:
    target_dir = out_dir if os.path.isabs(out_dir) else os.path.join(root, out_dir)
    os.makedirs(target_dir, exist_ok=True)
    written: List[str] = []
    for name, generator in _GENERATORS.items():
        content = generator(root)
        path = os.path.join(target_dir, name)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        written.append(path)
    return written
